-- Packer manager
require('plugins/packer-plugins') 
require('settings')
require('keymap')
-- Plugins 
require('plugins/colorscheme.onenord')
require('plugins/lualine-config')
require('plugins/nvim-tree-config')
require('plugins/telescope-config')
require('plugins/barbar-config')
require('plugins/vimtex')
require('plugins/lsp-installer')
require('plugins/lsp-config')
require('plugins/treesitter-config')
require('plugins/indentline-config')
require('plugins/toggleterm-config')
require('plugins/luasnippet')
require('plugins/cmp-config')
require('plugins/autopairs')
require('plugins/hop-config')
require('plugins/dash-config')
require('plugins/live-preview')
