-- Packer manager
require('plugins/packer-plugins') 
require('settings')
require('keymaps')
-- Plugins 
require('plugins/lualine-config')
require('plugins/colorscheme.onenord')
require('plugins/nvim-tree-config')
require('plugins/telescope-config')
require('plugins/barbar-config')
require('plugins/vimtex')
require('plugins/dash-config')
require('plugins/lsp-installer')
require('plugins/lsp-config')
require('plugins/treesitter-config')
require('plugins/indentline-config')
require('plugins/outline-config')
require('plugins/toggleterm-config')
